In [55]:
# ! pip install gensim               its installed

In [56]:
doc1 = "<br>Shep Schwab shopped at Scott’s Schnapps shop</br>; one shot of Scott’s Schnapps stopped Schwab’s watch."

doc2 = "Three Swedish switched witches watch three Swiss Swatch watches switches. Which Swedish switched witch watch which Swiss Swatch watch witch?"

doc3 = "Betty bought butter but the butter was bitter, 1243432 455454 so Betty bought better butter to make the bitter butter better."

doc4 = "Amidst the mists and coldest frosts, with stoutest wrists and loudest boasts, he thrusts his fist against the posts and still insists he sees the ghosts."

doc5 = "The sixth sick sheik’s sixth sheep’s sick. https://atkinsbookshelf.wordpress.com/2013/04/07/difficult-tongue-twisters/"

## import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
import pandas as pd
import re
import numpy as np

In [58]:
df=pd.DataFrame({'docs':[doc1,doc2,doc3,doc4,doc5]})

In [59]:
df

                                                docs
0  <br>Shep Schwab shopped at Scott’s Schnapps sh...
1  Three Swedish switched witches watch three Swi...
2  Betty bought butter but the butter was bitter,...
3  Amidst the mists and coldest frosts, with stou...
4  The sixth sick sheik’s sixth sheep’s sick. htt...

In [60]:
   data=pd.DataFrame ([["Biryani is <br> tasty <br>"], ["biryani <ul> is </ul> not Good"], ["I <ol> loved the Pizza"]],columns=["Review"])

In [61]:
data

                           Review
0      Biryani is <br> tasty <br>
1  biryani <ul> is </ul> not Good
2          I <ol> loved the Pizza

In [62]:
data['Review'].apply(lambda x:x.islower())

0    False
1    False
2    False
Name: Review, dtype: bool

In [63]:
x="Biryani is <br> tasty <br>"
re.findall("<.*?>",x) # non greedy version
# re.findall("<.*>",x) # greedy method

['<br>', '<br>']

In [64]:
data['Review'].apply(lambda x:True if re.search("<.*?>",x) else False).sum()
# serach gives a boolean value, so we use the if else 
# without if else
# data['Review'].apply(lambda x:re.search("<.*?>",x)) # will return boolean stuff

3

In [65]:
re.findall("http[s]?://.+?\S+","http://www.google.com/ https://innomatics.in")
# my logic
# if ? is not added its not greedy and its not that good

['http://www.google.com/', 'https://innomatics.in']

In [66]:
   data=pd.DataFrame ([["Biryani is <br> tasty <br>"], ["biryani <ul> is </ul> not Good"], ["I <ol> loved the Pizza http://www.google.com/"]],columns=["Review"])

In [67]:
data

                                          Review
0                     Biryani is <br> tasty <br>
1                 biryani <ul> is </ul> not Good
2  I <ol> loved the Pizza http://www.google.com/

In [68]:
data['Review'].apply(lambda x:True if re.search("http[s]?://.+?\S+",x) else False)

0    False
1    False
2     True
Name: Review, dtype: bool

In [69]:
data['Review'].apply(lambda x:True if re.search("http[s]?://.+?\S+",x) else False).sum()

1

In [70]:
# to check hastags and @ we use
re.findall("[@#].+?\s+",x)
data['Review'].apply(lambda x:True if re.search("[@#].+?\s+",x) else False)

0    False
1    False
2    False
Name: Review, dtype: bool

In [71]:
   data=pd.DataFrame ([["Biryani is <br> tasty ✌<br>"], ["biryani <ul> is </ul> not Good"], ["I <ol> loved the Pizza http://www.google.com/"]],columns=["Review"])

In [72]:
data

                                          Review
0                    Biryani is <br> tasty ✌<br>
1                 biryani <ul> is </ul> not Good
2  I <ol> loved the Pizza http://www.google.com/

In [73]:
!pip install emoji

Requirement already satisfied: emoji in c:\users\venka\anaconda3\lib\site-packages (2.14.0)

In [74]:
import emoji

In [75]:
emoji.emoji_count('Biryani is <br> tasty 🙌<br>')

1

In [48]:
emoji.demojize('Biryani is <br> tasty 🙌<br>')

'Biryani is <br> tasty :raising_hands:<br>'

In [49]:
 data['Review'].apply(lambda x:True if emoji.emoji_count(x)>0 else False)

0     True
1    False
2    False
Name: Review, dtype: bool

In [50]:
 data['Review'].apply(lambda x:True if emoji.emoji_count(x)>0 else False).sum()

1

In [51]:
re.findall("[.#&*^%@!0-9\]]","h43, h 4 , g6")

['4', '3', '4', '6']

In [52]:
x=["utf-8", "latin"]
for y in x:
    try:
        pd.read_csv(r"C:\Users\venka\OneDrive\Downloads\spam.csv", encoding=y, on_bad_lines="skip")
        print("{} is correct encoding".format(y))
    except UnicodeDecodeError:
        print("{} is not correct encoding".format(y))

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\venka\\OneDrive\\Downloads\\spam.csv'

In [76]:
df=pd.read_csv(r"C:\Users\venka\OneDrive\Downloads\spam.csv",encoding="latin",usecols=["v1","v2"])
# ,usecols=["v1","v2"]) used to define what are only the columns we need

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\venka\\OneDrive\\Downloads\\spam.csv'

In [77]:
dfc=df.copy()

In [78]:
dfc['v2']

KeyError: 'v2'

eda on the data using a function

In [ ]:
def seda(data, column):
    l=" ".join(dfc[column]).islower()
    html=dfc[column].apply(lambda x: True if re.search("<.*?>",x) else False).sum()
    urls=dfc[column].apply(lambda x: True if re.search("http[s]?://.+?\S+",x) else False).sum()
    men=data[column].apply(lambda x: True if re.search("[@#].+?\S+",x) else False).sum()
    emojss=dfc[column].apply(lambda x: True if emoji.emoji_count(x)>0 else False).sum()
    unn_char=data[column].apply(lambda x: True if re.search("[0-9]",x) else False).sum()
    if l==False:
        print("all the character are not in same case")
    if html>0:
        print("contains html")
    if urls>0:
        print("contains url")
    if men>0:
        print("contains mentions")
    if emojss>0:
        print("contains emojis")
    if unn_char>0:
        print("contains unn_charact")
# basic ideas
# can add all the new ideas here

In [ ]:
seda(dfc,"v2")

In [ ]:
dfc["v2"].apply(lambda x:True if re.search("http[s]?://.+?\S+",x) else False).sum()

In [ ]:
dfc[dfc["v2"].apply(lambda x:True if emoji.emoji_count(x)>0 else False)]

In [ ]:
dfc[dfc["v2"].apply(lambda x:True if re.search("http[s]?://.+?\S+",x) else False)]

Text cleaning

In [ ]:
## re.sub
# this is used to replace or substitute with the regex content we have provided

In [ ]:
import textblob
from textblob import TextBlob

In [ ]:
### User-defined Function to clean and preprocess the text
def text_clean(x,stem_lem = "stem"):
    ## converting into lower case
    x=x.lower()
    ## replacing html tags
    re.sub("<.*?>","",x)
    ## replace urls
    re.sub("http[s]?://.+?\S+",'',x)
    ## Replacing emoji
    x = emoji.demojize(x)
    x = re.sub(":.*?:","",x)
    ## Replacing special symbols
    x = re.sub("[^a-zA-Z0-9\s_]","",x)
    ## Spell corrector
    blob = TextBlob(x)
    x = str(blob.correct())
    ## Remove stopwords
    z = []
    for word in x.split():
        if word not in stopwords.words("english"):
            z.append(word)
   
    ## Stemming or Lemmatization
    if stem_lem == "stem":
        final = [snbstemmer.stem(ele) for ele in z]
    else:
        final = [lem.lemmatize(ele) for ele in z]
    return ' '.join(final)

In [ ]:
# to see the stopwords 
from nltk.corpus import stopwords
# from nltk only in corpus we import stopwords
stopwords.words('english')
# drop or remove the stopwords before using stemming or lemmitzation

In [ ]:
!pip install textblob
## bascically text blob is used to check spelling mistakes in the text

In [ ]:
!pip install nltk
## it is useed to install natural language toolkit for the steeming and lemmatization

In [ ]:
import nltk
from nltk.stem import SnowballStemmer
snbstemmer = SnowballStemmer('english')
# here by snowballstemmer we have created a object calles english

In [ ]:
# for cleaning we use a module from nltk called stem..and this module has different types of stemmers

In [ ]:
snbstemmer.stem('fucker')

In [ ]:
snbstemmer.stem('fucking')

In [ ]:
snbstemmer.stem('glitching')

In [ ]:
snbstemmer.stem('tits')

In [ ]:
snbstemmer.stem('nipples')

In [ ]:
# to use lemmatization these are the data required stuff
nltk.download('wordnet')
nltk.download('omw-1.4')
# wordnet itself contains all the english words so we no need to specify the language again

In [ ]:
from nltk.stem import WordNetLemmatizer
lem= WordNetLemmatizer()

In [ ]:
lem.lemmatize('nipples')

In [ ]:
snbstemmer.stem('nipples')

In [ ]:
# the difference btwn the stemming and lemmatization
# lematization return the correct form with meaningful words
# stemming returns no menaing ful words sometimes so we use only lematization everytime

In [ ]:
# day 10

In [ ]:
# !pip install scikit-learn

In [ ]:
import sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [ ]:
print(sns.get_dataset_names())
## seaborn has inbuilt datasets in it and we can check them by using this code. So we can directly load the data...

In [ ]:
df = sns.load_dataset("diamonds")

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df.select_dtypes(exclude="category")
## only the data with the Dtype category

In [ ]:
x=df.drop('price',axis=1)
y=df.price

In [ ]:
x.select_dtypes(exclude="category").columns
## to only know the column names in the data..

In [ ]:
# here we are just doing kde plot for each column
for col in x.select_dtypes(exclude="category").columns:
    print(col)
    plt.hist(x[col])
    plt.show()
    plt.boxplot(x[col])
    plt.show()

In [ ]:
# # now lets do scaling techniques
# 1. normalization (ntg but the MinMax scaling
# 2. Standardization
# 3. Robust scaling

In [ ]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.30,random_state = 42)

In [ ]:
x_train

In [ ]:
x_test

In [ ]:
# just a normal way to initialize the MinMaxScaler
mmscale=MinMaxScaler()

In [ ]:
mmscale # yeah it is initalized

In [ ]:
x_train_num= x_train.select_dtypes(exclude="category")
x_train_cat= x_train.select_dtypes(include="category")

In [ ]:
mmscale.fit(x_train_num)

In [ ]:

mmscale.transform(x_test_num)

In [ ]:
# so the data will be in the arrays so we have to convert them to datframe
x_train_num_transformed=pd.DataFrame(mmscale.transform(x_test_num),columns=x_train_num.columns)

In [ ]:
x_train_num_transformed

In [ ]:
# we hvae done for the train data now we have to lok out for the test data

In [ ]:
xtestnum=x_test.select_dtypes(exclude="category")
xtestcat=x_test.select_dtypes(include="category")

In [ ]:
xtestnum

In [ ]:
xtestcat

In [ ]:
mmscale.fit(xtestnum)

In [ ]:
X_test_num_transformed=pd.DataFrame(mmscale.transform(xtestnum),columns = xtestnum.columns)

In [ ]:
X_test_num_transformed

In [ ]:
for num_col in x_train_num.columns:
    print(num_col)
    plt.hist(x_train_num[num_col])#,density = True)
    plt.show()
    plt.hist(x_train_num_transformed[num_col])
    plt.show()

In [ ]:
# the main default in the process of using MinMax scaling is the outliers so we go for the standatization

## Stadardization

In [79]:
from sklearn.preprocessing import StandardScaler

In [80]:
sscale = StandardScaler()

In [81]:
sscale.fit(x_train_num)

NameError: name 'x_train_num' is not defined

In [82]:
sscale.mean_

AttributeError: 'StandardScaler' object has no attribute 'mean_'

In [ ]:
sscale.scale_

In [ ]:
sscale.var_

In [ ]:
x_train_num_std = pd.DataFrame(sscale.transform(x_train_num),columns = x_train_num.columns)

In [ ]:
x_train_num_std

In [ ]:
for num_col in x_train_num.columns:
    print(num_col)
    plt.hist(x_train_num[num_col])#,density = True)
    plt.show()
    plt.hist(x_train_num_std[num_col])
    plt.show()

In [ ]:
# so by using the standardization we simply use them to treat the sensitive outliers for the better one we use the robust scaling

## robust scaling

In [ ]:
# here we use mean and iqr(interquartile range) to deal with the outliers

In [ ]:
# # in this robust scaling we have a lot of transormations like
# 1. inverse transformation
# 2. log transformation
# 3. square transformatio
# 4. polynomial transformation
# 6. boxcox transormation
# 5. yeo jhonson transofromation
# # this 5 and 6 are already present in the sklearn classes we can use them in coding by using
# PowerTransformer()

In [ ]:
for num_col in x_train_num.columns:
    print(num_col)
    sns.kdeplot(x_train_num[num_col])#,density = True)
    plt.show()
    sns.kdeplot(x_train_num_std[num_col])
    plt.show()

In [ ]:
from sklearn.preprocessing import RobustScaler

In [ ]:
rscale=RobustScaler()

In [ ]:
rscale

In [ ]:
# we have imported the robust sclaer

In [ ]:
rnum=pd.DataFrame(rscale.fit_transform(x_train_num),columns=x_test_num.columns)

In [ ]:
rnum

In [ ]:
for num_col in x_train_num.columns:
    print(num_col)
    sns.kdeplot(x_train_num[num_col])#,density = True)
    plt.show()
    sns.kdeplot(rnum[num_col])
    plt.show()

In [ ]:
for num_col in x_train_num.columns:
    print(num_col)
    plt.hist(x_train_num[num_col])#,density = True)
    plt.show()
    plt.hist(rnum[num_col])
    plt.show()

In [ ]:
rscale.quantile_range
# these are the q1 and q2

In [ ]:
rscale.scale_
# the iqr is 0.64

In [ ]:
from sklearn.preprocessing import FunctionTransformer, PowerTransformer

In [ ]:
ft= FunctionTransformer(np.log10)
# this function transformer should be apPlied on the individual columns bcoz each have its own distrubition

In [ ]:
ft

In [ ]:
x_train_num_copy = x_train_num.copy()

In [ ]:
x_train_num_copy['carat']=ft.fit_transform(x_train_num['carat'])

In [ ]:
x_train_num_copy

In [ ]:
sns.kdeplot(x_train_num['carat'], color="red")
sns.kdeplot(x_train_num_copy['carat'])

In [ ]:
# inverse transformation
def inv_transform(x):
    return 1/x
ftinv= FunctionTransformer(inv_transform)
x_train_num_copy['carat']=ftinv.fit_transform(x_train_num['carat'])

In [ ]:
sns.kdeplot(x_train_num['carat'], color="red")
sns.kdeplot(x_train_num_copy['carat'])

In [ ]:
# square transforamtion
def sqr_transform(x):
    return x**2
ftsqr= FunctionTransformer(sqr_transform)
x_train_num_copy['carat']=ftsqr.fit_transform(x_train_num['carat'])
sns.kdeplot(x_train_num['carat'], color="red")
sns.kdeplot(x_train_num_copy['carat'])

In [ ]:
# square root transforamtion
def sqrt_transform(x):
    return x**0.5
ftsqrt= FunctionTransformer(sqrt_transform)
x_train_num_copy['carat']=ftsqrt.fit_transform(x_train_num['carat'])
sns.kdeplot(x_train_num['carat'], color="red")
sns.kdeplot(x_train_num_copy['carat'])

In [ ]:
# boxcox transformation
ptboxcox=PowerTransformer(method="box-cox")

In [ ]:
ptboxcox # the other method is yeo jhonson

In [ ]:
bc=ptboxcox.fit_transform(np.array(x_train_num['carat']).reshape(-1,1))

In [ ]:
x_train_num_copy['carat']=ptboxcox.fit_transform(np.array(x_train_num['carat']).reshape(-1,1))

In [ ]:
sns.kdeplot(x_train_num['carat'], color="red")
sns.kdeplot(x_train_num_copy['carat'])

In [ ]:
ptyj=PowerTransformer(method="yeo-johnson")

In [ ]:
x_train_num_copy['carat']=ptyj.fit_transform(np.array(x_train_num['carat']).reshape(-1,1))

In [ ]:
sns.kdeplot(x_train_num['carat'], color="red")
sns.kdeplot(x_train_num_copy['carat'])

In [ ]:
# food reviews
### its the green bucket biriyani reviews in vanasthalipuram
df=pd.read_csv(r"C:\Users\venka\food_reviews.csv")

In [ ]:
col=['review_text','rating']
df=df[col]

In [ ]:
df

#### lets do some fit and transform and perform the bow and tfidf in coding

In [ ]:
# theory part is present in the class notes..

In [ ]:
import sklearn

In [ ]:
data=pd.DataFrame({"reviews":['That gurl looks so tasty','I can eat that gurl everyday','that gurl is just old meat']})

In [ ]:
data

In [ ]:
# so to intialize bow and tfidf we import classes from the libraries sklearn
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
## CountVectorizer=BOW
## TfidfVectorizer=TFIDF

In [ ]:
# bag of words using class cv

In [ ]:
cv=CountVectorizer()

In [ ]:
cv

In [ ]:
cv.fit(data['reviews'])

In [ ]:
cv.vocabulary_

In [ ]:
cv.transform(data["reviews"])

In [ ]:
cv.transform(data["reviews"]).toarray()
# this is a very bad practice we use sparse matrix for less useage of memory and if we use this then waste of sparse matrx
# by using this RAM memeory will becom high, so we use sparse matrix as it stores only not null values
# we use this only for the visualizationssp

In [ ]:
# we can simply perform the test and transform aafter creating the object
# above we have done in 2 steps
# we can do it in the single step

In [ ]:
vector=cv.fit_transform(data['reviews'])

In [ ]:
vector

In [ ]:
vector.toarray()
# bad Practice only for the visualization part

### the stop words can be removed by sklearn and nlp

In [ ]:
# for nlp we will ust nltk natural language tool kit
import nltk
from nltk.corpus import stopwords

In [ ]:
stp=stopwords.words("english")
print(len(stp))
stp.remove("not")
print(len(stp))

In [ ]:
cv=CountVectorizer(lowercase=True,stop_words=stp,analyzer="char")

In [ ]:
cv.fit(data['reviews'])

In [ ]:
cv.get_feature_names_out()

In [ ]:
cv.vocabulary_
# char tokenization while using analyzer also counts spaces

In [ ]:
cv=CountVectorizer(lowercase=True,stop_words=stp,analyzer="word",min_df=1)

In [ ]:
cv.fit(data['reviews'])

In [ ]:
cv.get_feature_names_out()

In [ ]:
cv.vocabulary_

In [ ]:
# the main paramters of the countvectorizer(bow) are lowercase, stopwords, analyzer, min_df, max_df, max_features and binary(bbow)

## min_df

In [ ]:

cv=CountVectorizer(lowercase=True,stop_words=stp,analyzer="word",min_df=2)

In [ ]:
cv.fit(data['reviews'])

In [ ]:
cv.get_feature_names_out()

In [ ]:
cv.vocabulary_
# gurl is repeated more than 2 times so its more than 2 so its 3

## max_df

In [ ]:
cv=CountVectorizer(lowercase=True,stop_words=stp,analyzer="word",max_df=3)

In [ ]:
cv.fit(data['reviews'])

In [ ]:
cv.get_feature_names_out()

In [ ]:
cv.vocabulary_

## max_features

In [ ]:
cv=CountVectorizer(lowercase=True,stop_words=stp,analyzer="word",max_features=3)

In [ ]:
cv.fit(data['reviews'])

In [ ]:
cv.get_feature_names_out()

In [ ]:
cv.vocabulary_
# the values is 3 so 3 times

### binary box of words

In [ ]:
cv=CountVectorizer(lowercase=True,stop_words=stp,analyzer="word",max_features=3,binary=True)

In [ ]:
vv=cv.fit_transform(data['reviews'])

In [ ]:
vv.toarray()

# tfidf

In [ ]:
# tfidf has the same parameters as the bow

In [ ]:
tf=TfidfVectorizer()

In [ ]:
tf

In [ ]:
tf.fit_transform(data['reviews'])

In [ ]:
# the tfidf resultatnt values will always range in between 0 and 1 because of # smooth_idf and # norm parameters
tf.fit_transform(data['reviews']).toarray()

In [ ]:
tf.vocabulary_

In [ ]:
# smooth_idf formula is=log((N+1)/(n+1))+1
tf=TfidfVectorizer(smooth_idf=False)

In [ ]:
# # we use smmoth idf because some times we train data with limited data if there is a data that is new while trainging the result will be
# log(N/0) so as we are using python we will get zero division error so to avoid that we just use smoothidf to avoid this issue

In [ ]:
tf.fit_transform(data['reviews']).toarray()

In [ ]:
data['reviews']

In [ ]:
tf.vocabulary_

In [ ]:
tf=TfidfVectorizer(smooth_idf=True) 
tf.fit_transform(data['reviews']).toarray()

In [ ]:
# normalization  -- it has l2=sqrt and l1=mod

In [ ]:
# # THE idf value limits in the range of 0 to +infinity so the machine will be biased to the highest values so to adress and remove the 
# problem we just use normalizaton and these will returen the values in the range of 0 and 1

In [ ]:
tf=TfidfVectorizer(norm='l2') #by default if its true it uses l2
# by default the smoothidf will always be true and use l2

In [ ]:
tf.fit_transform(data['reviews'])

In [ ]:
tf.fit_transform(data['reviews']).toarray()

In [ ]:
tf=TfidfVectorizer(norm=None)
tf.fit_transform(data['reviews'])

In [ ]:
tf.fit_transform(data['reviews']).toarray()
# see there are values greater than 1 so the machine will be more biased to the value which is highest so we use normalization
# so they range in between 0 and 1

In [ ]:
# the bow and tfidf have been old methods so we are using word ambeddig method
# it has types which are advaced form of converting text to vectors

## word ambedding techniques
#### 1.Word2vec

In [ ]:
# to use word2vec(w2c) we cannot use sklearn, it does provide the modules for w2c so we use gensim library
import gensim

In [ ]:
from gensim.models import KeyedVectors,Word2Vec
# KeyedVectors for the pretrained models
# Word2Vec for the your own model

In [ ]:
model=KeyedVectors.load_word2vec_format(r"C:\Users\venka\OneDrive\Downloads\GoogleNews-vectors-negative300.bin\GoogleNews-vectors-negative300.bin",binary=True)
# as we are using binary extenstion .bin ## they keyedvectors only use binary extension so we have to use parameter binary=True

In [ ]:
model
# heres the data

In [ ]:
model.key_to_index #vocabulary

In [ ]:
len(model.key_to_index)

In [ ]:
model['the']

In [ ]:
model['the'].shape

In [ ]:
# any new words are present other than in the data 
# we get key error
# model['aldkfnaodf'].shape    method 1
# 'aldkfnaodf' in model.key_to_index

In [ ]:
# to check the similariry meaning or relationship (similairty btwn the words)
model.similar_by_word("king")

In [ ]:
# TO GET only top 5 similar words
model.similar_by_word("king",topn=5)

In [ ]:
model.similar_by_word("Sunny")
# cosine similiarity

In [ ]:
# cosine distace    it is calculated between 2 words
model.distance("king","kings")
# more similar so less distance

In [ ]:
model.distance("king","queen")
# king and kigns has less distance due to more similarity not like king and queen

In [ ]:
data=pd.DataFrame({"c":["king is very good","queen is beautiful"]})

In [ ]:
# code for the avgw2c and it can be done by tfidf also it is called Tfidf word2vec
final_data=[]
for doc in data["c"]:
    l=[]
    for word in doc.split():
        if word in model.index_to_key:   
            l.append(model[word])
    final_data.append(np.sum(np.array(l),axis=0)/len(l))

In [ ]:
len(final_data)

In [ ]:
np.array(final_data).shape

In [ ]:
pd.DataFrame(np.array(final_data))
# average word2vec output

In [ ]:
len(l)
# these are the 4 words stored here

In [ ]:
np.array(l).shape

In [ ]:
ff=np.array(l)
# we covert to array so that we can perform the element wise operation

In [ ]:
np.sum(ff,axis=0)/4
# this p is just an explanation

In [ ]:
# so letdo tfidfw2v
# steps
# 1.lets gather data

In [ ]:
data=pd.DataFrame({"c":["king is very good","queen is beautiful"]})
data

In [ ]:
tfidf=tf.fit_transform(data['c'])
vocabulary=tf.vocabulary_

In [ ]:
# this the method for the tfidfword2vec 
# by simply modifyig the above avafword2vec but i failed the try so this is the one
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Sample data
data = pd.DataFrame({"c": ["king is very good", "queen is beautiful"]})

# Fit TF-IDF Vectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['c'])
feature_names = tfidf.get_feature_names_out()

# Map words to their TF-IDF scores
word_to_tfidf = {word: tfidf_matrix[:, idx].toarray().flatten() for idx, word in enumerate(feature_names)}

# Get Word2Vec dimension
vector_size = model.vector_size

# Generate TF-IDF weighted vectors
final_data = [
    np.sum(
        [model[word] * word_to_tfidf[word][doc_idx] for word in doc.split() if word in model.index_to_key and word in word_to_tfidf],
        axis=0,
    ) / np.sum([word_to_tfidf[word][doc_idx] for word in doc.split() if word in model.index_to_key and word in word_to_tfidf])
    if any(word in model.index_to_key and word in word_to_tfidf for word in doc.split()) else np.zeros(vector_size)
    for doc_idx, doc in enumerate(data['c'])
]

In [ ]:
# avgword2vec
final_data=[]
for doc in data["c"]:
    l=[]
    for word in doc.split():
        if word in model.index_to_key:   
            l.append(model[word])
    final_data.append(np.sum(np.array(l),axis=0)/len(l))

In [ ]:
# # tfidfword2vec
# ### wordcode written by lavanya ji
# tfidf_w2v=[]

# for col,doc in enumerate(bbc['content']):
#     l=[]
#     sum=0
#     for word in doc.split():
#         if word in model1.wv and word in tf1.vocabulary_:
#             l.append(model1.wv[word]*tf2[col][tf1.vocabulary_[word]])
#             sum+=tf2[col][tf1.vocabulary_[word]]
#     tfidf_w2v.append(np.sum(np.array(l),axis=0)/sum)

###### creating our own w2v model
###### and in real life we have train our own w2v model

In [ ]:
# this is the data
bbc=pd.read_csv(r"C:\Users\venka\OneDrive\Documents\Downloads\archive (4)\bbc-news-data.csv",on_bad_lines='skip',delimiter='\t')

In [ ]:
final=bbc['content'].str.split().tolist()

In [ ]:
len(final)

In [ ]:
w2v = Word2Vec(window=3,vector_size=10,min_count=0,sg=0)

In [ ]:
w2v.build_vocab(final)

In [ ]:
w2v.train(final,total_examples=2225,epochs=3)
# The output (2046025, 2528730) means:
# 2046025: Words successfully used in training.
# 2528730: Words skipped (not in the model's vocabulary or filtered out).

In [ ]:
w2v.wv['news']
# to find the vocabulary present in the data or not 
# if its not there, it will get a Key error

In [ ]:
w2v.wv.similar_by_word("power",topn=5)

In [ ]:
# here we save the model to our pc
w2v.save(r'C:\Users\venka\OneDrive\My Stuff\Sun01\ml learning junk\bbcstuff.bin')

In [ ]:
model1=Word2Vec.load(r"C:\Users\venka\OneDrive\My Stuff\Sun01\ml learning junk\bbcstuff.bin")

In [ ]:
model1

In [ ]:
#Average w2v
avg_w2v=[]
for document in final:
    l=[]
    for word in document:
        l.append(model1.wv[word])
    avg_w2v.append(np.sum(np.array(l),axis=0)/len(l))

In [ ]:
## here we convert into DataFrame to see the results
pd.DataFrame(avg_w2v)

In [ ]:
# we did the avgword2vec now lets do the tfidfword2vec
tf=TfidfVectorizer()
tf.fit(bbc['content'])

In [ ]:
tff=tf.transform(bbc['content']).toarray()

In [ ]:
tff

In [ ]:
tf.vocabulary_

In [ ]:
tfidf_w2v=[]
for col,doc in enumerate(bbc['content']):
    l=[]
    sum=0
    for word in doc.split():
        if word in model1.wv and word in tf.vocabulary_:
            l.append(model1.wv[word]*tff[col][tf.vocabulary_[word]])
            sum+=tff[col][tf.vocabulary_[word]]
    tfidf_w2v.append(np.sum(np.array(l),axis=0)/sum)

In [ ]:
pd.DataFrame(tfidf_w2v)
## so here is the result...

###### end of bbc assignment
###### ########## need to practice more about these word2vec

# better to make detailed notes of all the topics and details

# need to work more sunny you can do this and u have to mannnnnnn
### no issues taking help from others your leaning and never stop it and keep learning and keep  practicing

#### the above 15 days classes are okay just need to revise better for ml.
#### and from now we will try to be more precise and clear.....

# Day 16
###### fasttext

In [ ]:
# to use the fast text we have its own library in python called fasttext.wheel

In [ ]:
# pip install fasttext.wheel

###### pretrained model

In [ ]:
import fasttext

In [ ]:
# to load the data from pc
model1=fasttext.load_model(r"C:\Users\venka\OneDrive\Documents\sunny\certificates\data from web\cc.en.300.bin\cc.en.300.bin")

In [ ]:
model1

In [ ]:
model1.get_word_vector("happy")

In [ ]:
model.get_nearest_neighbors("happy")
# to get the nearest neighbour

In [ ]:
# the ram is not sufficent to load this large file
# and to convert to vector, we use same methods ie., avgword2vec and tfidfword2vec

In [ ]:
## * the word2vec fast testing mainly depends mainly on the corpus or the dataset ***

In [ ]:
# fast text can find or relate more sematic meaning than the word2vec

In [ ]:
# it will preserve semantic meaning by context knowledge, they store avg semantic meaning
# but if we use llms it does not give avg semantic meaning it gives the sematic meaning like humans

##### our trained model

In [ ]:
bbc=pd.read_csv(r"C:\Users\venka\OneDrive\Documents\Downloads\archive (4)\bbc-news-data.csv",on_bad_lines='skip',delimiter='\t')

In [ ]:
bbc

In [ ]:
bbc["content"].to_csv(r"C:\Users\venka\OneDrive\Documents\Downloads\archive (4)\bbc-final-data.csv")

In [ ]:
finalmdoel=fasttext.train_unsupervised(input=r"C:\Users\venka\OneDrive\Documents\Downloads\archive (4)\bbc-final-data.csv",model="cbow",dim=10,epoch=3)

In [ ]:
finalmdoel.get_word_vector("scarlet witch")

In [ ]:
finalmdoel.get_sentence_vector("sunny is hot")
# it can convert a sentence into vector no paragraph 
# only avialbe in fast text no word2vev

In [54]:
finalmdoel.get_input_matrix()

NameError: name 'finalmdoel' is not defined

In [53]:
finalmdoel.get_input_matrix().shape

NameError: name 'finalmdoel' is not defined